# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: files
          path: ./song.txt

      # -d '{"event_type": "trigger-workflow", "client_payload": {"artifact_name": "my-artifact", "other_data": "value"}}' 
      - name: Run a multi-line script
        run: |
          curl -X POST \
          -H "Authorization: token ${{ secrets.PERSONAL_ACCESS_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          -d '{"tag_name": "latest-build", "name": "Latest ${{ github.ref }}", "draft": false, "prerelease": false}' \
          https://api.github.com/repos/projecttrails/trails-deploy/releases

      - name: Upload file to remote release
        run: |
          RELEASE_ID=$(curl -s -H "Authorization: token ${{ secrets.PERSONAL_ACCESS_TOKEN }}" \
          https://api.github.com/repos/projecttrails/trails-deploy/releases/tags/latest-build | jq -r .id)
      
          curl -X POST \
          -H "Authorization: token ${{ secrets.PERSONAL_ACCESS_TOKEN }}" \
          -H "Content-Type: application/octet-stream" \
          --data-binary @song.txt \
          "https://uploads.github.com/repos/projecttrails/trails-deploy/releases/$RELEASE_ID/assets?name=song.txt"

      - name: Trigger workflow in another repo
        run: |
          curl -X POST \
          -H "Authorization: token ${{ secrets.PERSONAL_ACCESS_TOKEN }}" \
          -d '{"ref": "fix", "inputs": {"artifact_url": "https://github.com/projecttrails/trails-deploy/releases/latest/download/song.txt"}}' \
          https://api.github.com/repos/projecttrails/trails-deploy/actions/workflows/deploy_api.yml/dispatches          

          

      # Runs a set of commands using the runners shell
      # -d '{"event_type": "trigger-workflow", "client_payload": {"artifact_name": "my-artifact", "other_data": "value"}}' 
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          curl -X POST \
          -H "Authorization: token ${{ secrets.PERSONAL_ACCESS_TOKEN }}" \
          -d '{"ref": "fix", "client_payload": {"artifact_name": "files", "branch": "${{ github.ref }}" }}' \
          https://api.github.com/repos/projecttrails/trails-deploy/actions/workflows/deploy_api.yml/dispatches
